#!/usr/bin/env bash

# Run tests
# See https://github.com/github/scripts-to-rule-them-all

set -eou pipefail

# navigate to root of repo
pushd $(git rev-parse --show-toplevel) > /dev/null

npm test -- $@

# back to where we were
popd > /dev/null