#!/usr/bin/env bash

# Update after pulling new changes
# See https://github.com/github/scripts-to-rule-them-all

set -eou pipefail

# navigate to root of repo
pushd $(git rev-parse --show-toplevel) > /dev/null

script/bootstrap

# back to where we were
popd > /dev/null