#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

_STASH_NAME="husky.pre-push.$(date +%s)"

echo "* Stashing uncommited changes ($_STASH_NAME)"
git stash push --include-untracked --message "$_STASH_NAME"

echo "* Pulling main from upstream"
git pull --rebase upstream main
./script/update

echo "* Running tests"
if ! ./script/test ; then
  echo '  - Committed changes do not pass tests, please fix before pushing.'
  echo '    Your uncommitted changes are stashed and can be restored by'
  echo '    running `git stash pop`.'
  false
fi

if git stash list | grep "$_STASH_NAME"; then
  echo "* Restoring stashed changes ($_STASH_NAME)"
  git stash pop $(git stash list | grep "$_STASH_NAME" | cut -d: -f1)
fi
